name: tests

on:
  push:
    branches:
      - dev

jobs:
  test:
    name: run tests
    runs-on: ubuntu-latest

    steps:
      - name: checkout code
        uses: actions/checkout@v2
      - name: install node
        uses: actions/setup-node@v2
      - name: tests
        run: |
          git config user.email "me@example.com"
          git config user.name "Me"
          cd about
          nvm use
          ./run.sh
