name: tests

on:
  push:
    branches:
      - dev

jobs:
  test:
    name: run tests
    runs-on: ubuntu-latest

    steps:
      - name: checkout code
        uses: actions/checkout@v2
      - name: git config
        run: |
          git config user.email "me@example.com"
          git config user.name "Me"
      - name: tests
        run: |
          cd about
          ./run.sh
